# src/SomeWork/MtsBundle/Resources/config/doctrine/Category.mongodb.yml
SomeWork\MtsBundle\Document\Category:
  type: document
  db: mts
  collection: categories
  fields:
    id:
      type: int
      id: true
      strategy: NONE
    name:
      type: string
  referenceMany:
    parentsCategory:
      targetDocument: SomeWork\MtsBundle\Document\Category
      cascade: all
      storeAs: dbRef
      strategy: setArray
    childrenCategory:
      targetDocument: SomeWork\MtsBundle\Document\Category
      cascade: all
      storeAs: dbRef
      strategy: setArray
    products:
      targetDocument: SomeWork\MtsBundle\Document\Product
      cascade: all
      storeAs: dbRef
      strategy: setArray