# src/SomeWork/MtsBundle/Resources/config/doctrine/Offer.mongodb.yml
SomeWork\MtsBundle\Document\Offer:
  type: document
  db: mts
  collection: offers
  fields:
    id:
      type: int
      id: true
      strategy: INCREMENT
    price:
      type: int
    currencyId:
      type: string
  referenceOne:
    product:
      targetDocument: SomeWork\MtsBundle\Document\Product
      cascade: all
      storeAs: dbRef