some_work_admin_app:
    resource: "@SomeWorkAdminAppBundle/Resources/config/routing.yml"
    prefix:   /

imports:
    resource: routing/sonata_admin.yml

some_work_mts:
    resource: "@SomeWorkYandexAppBundle/Resources/config/routing.yml"
    prefix:   /
